[package]
name = "rust_threads"
version = "0.1.0"
authors = ["farooq-azam-khan <farooq1.khan@ryerson.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam = "0.8.1"
rayon = "1.5.1"